from enum import Enum


class LifecycleStatus(str, Enum):
    DISCOVERED = "DISCOVERED"
    VERIFYING = "VERIFYING"
    VERIFIED = "VERIFIED"
    QUALIFIED = "QUALIFIED"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    OUTREACH_READY = "OUTREACH_READY"
    REJECTED = "REJECTED"
    REVERIFY_REQUIRED = "REVERIFY_REQUIRED"


class WebsiteStatus(str, Enum):
    OFFICIAL_WEBSITE = "OFFICIAL_WEBSITE"
    SOCIAL_ONLY = "SOCIAL_ONLY"
    DIRECTORY_ONLY = "DIRECTORY_ONLY"
    NO_WEBSITE_FOUND = "NO_WEBSITE_FOUND"
    CONFLICTING = "CONFLICTING"
    UNCERTAIN = "UNCERTAIN"


class SocialPlatform(str, Enum):
    FACEBOOK = "FACEBOOK"
    INSTAGRAM = "INSTAGRAM"
    LINKEDIN = "LINKEDIN"


class SocialStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    FOUND_UNVERIFIED = "FOUND_UNVERIFIED"
    SOCIAL_ONLY = "SOCIAL_ONLY"
    NOT_FOUND = "NOT_FOUND"


class ContactType(str, Enum):
    PHONE = "PHONE"
    EMAIL = "EMAIL"


class VerificationCheckType(str, Enum):
    NAME_MATCH = "NAME_MATCH"
    ADDRESS_MATCH = "ADDRESS_MATCH"
    PHONE_MATCH = "PHONE_MATCH"
    DOMAIN_MATCH = "DOMAIN_MATCH"
    SOCIAL_IDENTITY_MATCH = "SOCIAL_IDENTITY_MATCH"
    BUSINESS_ACTIVITY = "BUSINESS_ACTIVITY"
    WEBSITE_OWNERSHIP_SIGNAL = "WEBSITE_OWNERSHIP_SIGNAL"
    DUPLICATE_MATCH = "DUPLICATE_MATCH"


class VerificationResultStatus(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    UNKNOWN = "UNKNOWN"
    CONFLICT = "CONFLICT"


class EvidenceType(str, Enum):
    OBSERVED_FACT = "OBSERVED_FACT"
    SYSTEM_CLASSIFICATION = "SYSTEM_CLASSIFICATION"
    AI_RECOMMENDATION = "AI_RECOMMENDATION"


class OpportunityType(str, Enum):
    NEW_WEBSITE = "NEW_WEBSITE"
    WEBSITE_REDESIGN = "WEBSITE_REDESIGN"
    SEO = "SEO"
    LOCAL_SEO = "LOCAL_SEO"
    REDESIGN_PLUS_SEO = "REDESIGN_PLUS_SEO"
    SOCIAL_TO_WEBSITE = "SOCIAL_TO_WEBSITE"
    CONVERSION_OPTIMIZATION = "CONVERSION_OPTIMIZATION"
    COMPETITOR_GAP = "COMPETITOR_GAP"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class ReviewActionType(str, Enum):
    SELECT_TRUSTED = "SELECT_TRUSTED"
    EDIT = "EDIT"
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    UNRESOLVED = "UNRESOLVED"
    REVERIFY = "REVERIFY"


class TargetStatus(str, Enum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class TargetRunStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class JobStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    RETRYING = "RETRYING"


class ExportFormat(str, Enum):
    CSV = "CSV"
    EXCEL = "EXCEL"
