"""create_core_18_tables

Revision ID: 2d4dcc9437a5
Revises: None
Create Date: 2026-09-03 19:08:59.979312

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4dcc9437a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('DISCOVERED', 'VERIFYING', 'VERIFIED', 'QUALIFIED', 'HUMAN_REVIEW', 'OUTREACH_READY', 'REJECTED', 'REVERIFY_REQUIRED', name='lifecycle_status_enum'), nullable=False),
    sa.Column('business_confidence', sa.Float(), nullable=False),
    sa.Column('contact_confidence', sa.Float(), nullable=False),
    sa.Column('opportunity_confidence', sa.Float(), nullable=False),
    sa.Column('lead_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_category'), 'businesses', ['category'], unique=False)
    op.create_index(op.f('ix_businesses_city'), 'businesses', ['city'], unique=False)
    op.create_index(op.f('ix_businesses_country'), 'businesses', ['country'], unique=False)
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_index(op.f('ix_businesses_lead_score'), 'businesses', ['lead_score'], unique=False)
    op.create_index(op.f('ix_businesses_lifecycle_status'), 'businesses', ['lifecycle_status'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_index(op.f('ix_businesses_normalized_name'), 'businesses', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_businesses_phone'), 'businesses', ['phone'], unique=False)
    op.create_index(op.f('ix_businesses_state'), 'businesses', ['state'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('contacts',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PHONE', 'EMAIL', name='contact_type_enum'), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('normalized_value', sa.String(length=255), nullable=False),
    sa.Column('validity_status', sa.String(length=50), nullable=False),
    sa.Column('ownership_status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_business_id'), 'contacts', ['business_id'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_index(op.f('ix_contacts_normalized_value'), 'contacts', ['normalized_value'], unique=False)
    op.create_index(op.f('ix_contacts_type'), 'contacts', ['type'], unique=False)
    op.create_table('lead_scores',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('business_confidence', sa.Float(), nullable=False),
    sa.Column('contact_confidence', sa.Float(), nullable=False),
    sa.Column('opportunity_confidence', sa.Float(), nullable=False),
    sa.Column('lead_score', sa.Float(), nullable=False),
    sa.Column('rules_applied', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_scores_business_id'), 'lead_scores', ['business_id'], unique=False)
    op.create_index(op.f('ix_lead_scores_id'), 'lead_scores', ['id'], unique=False)
    op.create_index(op.f('ix_lead_scores_lead_score'), 'lead_scores', ['lead_score'], unique=False)
    op.create_index(op.f('ix_lead_scores_version'), 'lead_scores', ['version'], unique=False)
    op.create_table('opportunities',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('NEW_WEBSITE', 'WEBSITE_REDESIGN', 'SEO', 'LOCAL_SEO', 'REDESIGN_PLUS_SEO', 'SOCIAL_TO_WEBSITE', 'CONVERSION_OPTIMIZATION', 'COMPETITOR_GAP', 'MANUAL_REVIEW', name='opportunity_type_enum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('recommended_service', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_business_id'), 'opportunities', ['business_id'], unique=False)
    op.create_index(op.f('ix_opportunities_confidence'), 'opportunities', ['confidence'], unique=False)
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_type'), 'opportunities', ['type'], unique=False)
    op.create_table('social_profiles',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('FACEBOOK', 'INSTAGRAM', 'LINKEDIN', name='social_platform_enum'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('identity_match_score', sa.Float(), nullable=False),
    sa.Column('activity_status', sa.Enum('ACTIVE', 'INACTIVE', 'FOUND_UNVERIFIED', 'SOCIAL_ONLY', 'NOT_FOUND', name='social_status_enum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_profiles_business_id'), 'social_profiles', ['business_id'], unique=False)
    op.create_index(op.f('ix_social_profiles_id'), 'social_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_social_profiles_platform'), 'social_profiles', ['platform'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('verification_results',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('check_type', sa.Enum('NAME_MATCH', 'ADDRESS_MATCH', 'PHONE_MATCH', 'DOMAIN_MATCH', 'SOCIAL_IDENTITY_MATCH', 'BUSINESS_ACTIVITY', 'WEBSITE_OWNERSHIP_SIGNAL', 'DUPLICATE_MATCH', name='verification_check_type_enum'), nullable=False),
    sa.Column('result', sa.Enum('PASS', 'FAIL', 'UNKNOWN', 'CONFLICT', name='verification_result_status_enum'), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_results_business_id'), 'verification_results', ['business_id'], unique=False)
    op.create_index(op.f('ix_verification_results_check_type'), 'verification_results', ['check_type'], unique=False)
    op.create_index(op.f('ix_verification_results_id'), 'verification_results', ['id'], unique=False)
    op.create_index(op.f('ix_verification_results_result'), 'verification_results', ['result'], unique=False)
    op.create_table('websites',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('OFFICIAL_WEBSITE', 'SOCIAL_ONLY', 'DIRECTORY_ONLY', 'NO_WEBSITE_FOUND', 'CONFLICTING', 'UNCERTAIN', name='website_status_enum'), nullable=False),
    sa.Column('ownership_signal', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_business_id'), 'websites', ['business_id'], unique=True)
    op.create_index(op.f('ix_websites_domain'), 'websites', ['domain'], unique=False)
    op.create_index(op.f('ix_websites_id'), 'websites', ['id'], unique=False)
    op.create_index(op.f('ix_websites_status'), 'websites', ['status'], unique=False)
    op.create_table('evidence',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_url_or_id', sa.String(length=500), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('evidence_type', sa.Enum('OBSERVED_FACT', 'SYSTEM_CLASSIFICATION', 'AI_RECOMMENDATION', name='evidence_type_enum'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('verification_result_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_result_id'], ['verification_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_business_id'), 'evidence', ['business_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_type'), 'evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_source'), 'evidence', ['source'], unique=False)
    op.create_index(op.f('ix_evidence_status'), 'evidence', ['status'], unique=False)
    op.create_table('exports',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('format', sa.Enum('CSV', 'EXCEL', name='export_format_enum'), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('lead_ids', sa.JSON(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_created_by_id'), 'exports', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_exports_id'), 'exports', ['id'], unique=False)
    op.create_index(op.f('ix_exports_status'), 'exports', ['status'], unique=False)
    op.create_table('review_actions',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('before_value', sa.JSON(), nullable=False),
    sa.Column('after_value', sa.JSON(), nullable=False),
    sa.Column('action_type', sa.Enum('SELECT_TRUSTED', 'EDIT', 'APPROVE', 'REJECT', 'UNRESOLVED', 'REVERIFY', name='review_action_type_enum'), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_actions_action_type'), 'review_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_review_actions_business_id'), 'review_actions', ['business_id'], unique=False)
    op.create_index(op.f('ix_review_actions_id'), 'review_actions', ['id'], unique=False)
    op.create_index(op.f('ix_review_actions_reviewer_id'), 'review_actions', ['reviewer_id'], unique=False)
    op.create_table('seo_audits',
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('meta_description', sa.String(length=1000), nullable=True),
    sa.Column('headings_summary', sa.JSON(), nullable=False),
    sa.Column('indexable', sa.Boolean(), nullable=False),
    sa.Column('canonical_url', sa.String(length=500), nullable=True),
    sa.Column('sitemap_present', sa.Boolean(), nullable=False),
    sa.Column('robots_present', sa.Boolean(), nullable=False),
    sa.Column('image_alt_coverage', sa.Float(), nullable=False),
    sa.Column('schema_types', sa.JSON(), nullable=False),
    sa.Column('local_seo_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_audits_business_id'), 'seo_audits', ['business_id'], unique=False)
    op.create_index(op.f('ix_seo_audits_id'), 'seo_audits', ['id'], unique=False)
    op.create_index(op.f('ix_seo_audits_website_id'), 'seo_audits', ['website_id'], unique=True)
    op.create_table('targets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('niche', sa.String(length=100), nullable=False),
    sa.Column('sub_niche', sa.String(length=100), nullable=True),
    sa.Column('geography', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='target_status_enum'), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('opportunity_types', sa.JSON(), nullable=False),
    sa.Column('source_configuration', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_geography'), 'targets', ['geography'], unique=False)
    op.create_index(op.f('ix_targets_id'), 'targets', ['id'], unique=False)
    op.create_index(op.f('ix_targets_name'), 'targets', ['name'], unique=False)
    op.create_index(op.f('ix_targets_niche'), 'targets', ['niche'], unique=False)
    op.create_table('website_audits',
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('https_enabled', sa.Boolean(), nullable=False),
    sa.Column('responsive_mobile', sa.Boolean(), nullable=False),
    sa.Column('cta_visible', sa.Boolean(), nullable=False),
    sa.Column('contact_visible', sa.Boolean(), nullable=False),
    sa.Column('navigation_quality', sa.String(length=50), nullable=False),
    sa.Column('broken_links_count', sa.Integer(), nullable=False),
    sa.Column('trust_signals_score', sa.Float(), nullable=False),
    sa.Column('service_coverage', sa.JSON(), nullable=False),
    sa.Column('location_coverage', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_audits_business_id'), 'website_audits', ['business_id'], unique=False)
    op.create_index(op.f('ix_website_audits_id'), 'website_audits', ['id'], unique=False)
    op.create_index(op.f('ix_website_audits_website_id'), 'website_audits', ['website_id'], unique=True)
    op.create_table('target_runs',
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='target_run_status_enum'), nullable=False),
    sa.Column('total_discovered', sa.Integer(), nullable=False),
    sa.Column('total_verified', sa.Integer(), nullable=False),
    sa.Column('total_qualified', sa.Integer(), nullable=False),
    sa.Column('total_human_review', sa.Integer(), nullable=False),
    sa.Column('total_outreach_ready', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_log', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_runs_id'), 'target_runs', ['id'], unique=False)
    op.create_index(op.f('ix_target_runs_target_id'), 'target_runs', ['target_id'], unique=False)
    op.create_table('jobs',
    sa.Column('target_run_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'RETRYING', name='job_status_enum'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('error_log', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_run_id'], ['target_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_target_run_id'), 'jobs', ['target_run_id'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('source_records',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('target_run_id', sa.UUID(), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_identifier', sa.String(length=255), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_run_id'], ['target_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_records_business_id'), 'source_records', ['business_id'], unique=False)
    op.create_index(op.f('ix_source_records_id'), 'source_records', ['id'], unique=False)
    op.create_index(op.f('ix_source_records_source_name'), 'source_records', ['source_name'], unique=False)
    op.create_index(op.f('ix_source_records_target_run_id'), 'source_records', ['target_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_records_target_run_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_source_name'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_business_id'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_target_run_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_idempotency_key'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_target_runs_target_id'), table_name='target_runs')
    op.drop_index(op.f('ix_target_runs_id'), table_name='target_runs')
    op.drop_table('target_runs')
    op.drop_index(op.f('ix_website_audits_website_id'), table_name='website_audits')
    op.drop_index(op.f('ix_website_audits_id'), table_name='website_audits')
    op.drop_index(op.f('ix_website_audits_business_id'), table_name='website_audits')
    op.drop_table('website_audits')
    op.drop_index(op.f('ix_targets_niche'), table_name='targets')
    op.drop_index(op.f('ix_targets_name'), table_name='targets')
    op.drop_index(op.f('ix_targets_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_geography'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_seo_audits_website_id'), table_name='seo_audits')
    op.drop_index(op.f('ix_seo_audits_id'), table_name='seo_audits')
    op.drop_index(op.f('ix_seo_audits_business_id'), table_name='seo_audits')
    op.drop_table('seo_audits')
    op.drop_index(op.f('ix_review_actions_reviewer_id'), table_name='review_actions')
    op.drop_index(op.f('ix_review_actions_id'), table_name='review_actions')
    op.drop_index(op.f('ix_review_actions_business_id'), table_name='review_actions')
    op.drop_index(op.f('ix_review_actions_action_type'), table_name='review_actions')
    op.drop_table('review_actions')
    op.drop_index(op.f('ix_exports_status'), table_name='exports')
    op.drop_index(op.f('ix_exports_id'), table_name='exports')
    op.drop_index(op.f('ix_exports_created_by_id'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_evidence_status'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_source'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_business_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_websites_status'), table_name='websites')
    op.drop_index(op.f('ix_websites_id'), table_name='websites')
    op.drop_index(op.f('ix_websites_domain'), table_name='websites')
    op.drop_index(op.f('ix_websites_business_id'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_verification_results_result'), table_name='verification_results')
    op.drop_index(op.f('ix_verification_results_id'), table_name='verification_results')
    op.drop_index(op.f('ix_verification_results_check_type'), table_name='verification_results')
    op.drop_index(op.f('ix_verification_results_business_id'), table_name='verification_results')
    op.drop_table('verification_results')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_social_profiles_platform'), table_name='social_profiles')
    op.drop_index(op.f('ix_social_profiles_id'), table_name='social_profiles')
    op.drop_index(op.f('ix_social_profiles_business_id'), table_name='social_profiles')
    op.drop_table('social_profiles')
    op.drop_index(op.f('ix_opportunities_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_confidence'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_business_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_lead_scores_version'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_lead_score'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_id'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_business_id'), table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_index(op.f('ix_contacts_type'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_normalized_value'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_business_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_businesses_state'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_phone'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_normalized_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_lifecycle_status'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_lead_score'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_country'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_city'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_category'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
